"use client";
import { useEffect,useState } from "react";
import { Copy,Gift,MessageCircle,X } from "lucide-react";
import { createClient } from "@/lib/supabase/client";
export function CreatorActions({compact=false}:{compact?:boolean}){
 const [open,setOpen]=useState(false);const [details,setDetails]=useState<{creator_name:string;card_number:string|null}|null>(null);
 useEffect(()=>{if(!open||details)return;void createClient().from("site_settings").select("creator_name,card_number").eq("id","creator_support").single().then(({data})=>setDetails(data))},[open,details]);
 return <><div className={`flex flex-wrap ${compact?"gap-2":"justify-center gap-3"}`}><a href="https://t.me/lonedevs" target="_blank" className="inline-flex items-center gap-2 rounded-full border border-[#cdbdaf] bg-white/70 px-4 py-2.5 text-sm"><MessageCircle size={16}/>Yaratuvchi bilan bog‘lanish</a><button onClick={()=>setOpen(true)} className="inline-flex items-center gap-2 rounded-full bg-[#a4775a] px-4 py-2.5 text-sm font-semibold text-white"><Gift size={16}/>Loyihani qo‘llab-quvvatlash</button></div>
 {open&&<div role="dialog" aria-modal="true" aria-label="Qo‘llab-quvvatlash ma’lumotlari" className="fixed inset-0 z-50 grid place-items-center bg-black/45 px-5" onMouseDown={(e)=>{if(e.target===e.currentTarget)setOpen(false)}}><div className="relative w-full max-w-md rounded-3xl bg-[#f8f4ed] p-7 text-[#302820] shadow-2xl"><button aria-label="Yopish" onClick={()=>setOpen(false)} className="absolute right-4 top-4 rounded-full border p-2"><X size={16}/></button><Gift className="text-[#a4775a]"/><h2 className="mt-4 font-serif text-3xl">Loyihani qo‘llab-quvvatlash</h2><p className="mt-2 text-sm leading-6 text-[#766a61]">Taklif platformasini rivojlantirish uchun ixtiyoriy yordam.</p>{details?.card_number?<div className="mt-6 rounded-2xl border bg-white p-5"><p className="text-xs uppercase tracking-wider text-[#8a8179]">Karta egasi</p><p className="mt-1 font-semibold">{details.creator_name}</p><button onClick={()=>navigator.clipboard.writeText(details.card_number!)} className="mt-4 flex w-full items-center justify-between rounded-xl bg-[#f1ece7] px-4 py-3 font-mono"><span>{details.card_number}</span><Copy size={16}/></button></div>:<p className="mt-6 rounded-2xl border bg-white p-5 text-sm">{details?"Karta ma’lumoti hali kiritilmagan. Uni Sozlamalar sahifasida qo‘shish mumkin.":"Yuklanmoqda…"}</p>}</div></div>}</>
}
